### ISSUE TITLE
CharacterNames Generation problem

### ISSUE THREAD

**Issue by im8otto** [EssenceDBD/MarketUpdater#1]
Hi, I think that Character Names should be [CharacterId] Character Name
For example K01 is Chuckles, to do this in CUE4Parse.cs I added after `Provider.Mount()`
`Provider.LoadLocalization();`
And instead of `characterNames.Add($"{property?["DebugName"]}");`
`characterNames.Add($"[{property?["CharacterId"]}] {property?["DisplayName"]["SourceString"]}");`

What do you think?
Sorry I don't use Github a lot, idk if Issue is correct way to comunicate this.
Have a nice day!

**Comment by EssenceDBD** [comment]
Thanks for another helpful suggestion -- source has been updated with changes.

Issue is fine, or you can clone the repository and make changes then submit a pull request for changes that you make that I can then add directly.

Also, my discord is 'bhvr' if you would like to communicate easier for further enquiries.

Hope you have a great day <3
